### ISSUE TITLE
The skin icon with the label domain.xx/assets/addons/d2u_videos/minimal_skin_dark/rewind.png can't be laoded. check path!

### ISSUE THREAD

**Issue by andreasKrauseWebular** [TobiasKrais/d2u_videos#1]
Hey i have a 
REDAXO 5.6.4
PHP 7.0.32
Trying to test the d2u_video Addon i found that issue;

 The skin icon with the label domain.xx/assets/addons/d2u_videos/minimal_skin_dark/rewind.png can't be laoded. check path! 

I have to admit that i just copied the .js out of the example because i first want to test it before i buy it.

The player starts but it brings up the message above

**Comment by andreasKrauseWebular** [comment]
Solved by loading js file from here: https://www.kaltenbach.com/de/medien/videos/#/?playlistId=0&videoId=0

Maybe there is a bug with the news Version of the js file

**Comment by TobiasKrais** [comment]
New images added. Thanks for the bug report! Should be solved now.

**Comment by andreasKrauseWebular** [comment]
will there be a new version for the redaxo addon so that i can update over the installer?

**Comment by andreasKrauseWebular** [comment]
And thank you for the quick fix!!!

**Comment by TobiasKrais** [comment]
Not now. I do not release for every change. Just download via "Clone or Download" button from repos startpage and upload all files from assets folder to your assets folder.

**Comment by andreasKrauseWebular** [comment]
ok - thank you for the quick help
